Homework1.Sorting
AlexPoziev/SPBUHomeworkCSharp pull request #1
Opened 2023-02-18 09:48 UTC by AlexPoziev

2023-02-21 20:12 UTC, victoriafomina requested changes

2023-02-21 20:24 UTC, victoriafomina commented on Homework1/Sorting/Sorting/ShellSort.cs
> +		private static void Swap(ref int First, ref int Second)
Названия аргументов методов со строчной буквы должны начинаться

2023-02-21 20:43 UTC, AlexPoziev commented on Homework1/Sorting/SortingTest/ShellSortTest.cs
> +        Assert.That(IsArraySorted(array), Is.True);
При данном способе написания IDE советует писать [так](https://github.com/nunit/nunit.analyzers/blob/master/documentation/NUnit2003.md)

2023-02-21 22:56 UTC, victoriafomina requested changes

2023-02-21 22:56 UTC, victoriafomina commented on Homework1/Sorting/Sorting/ArrayUtils.cs
> +﻿namespace Sorting;
Нужна пустая строка после _namespace_

2023-02-21 22:56 UTC, victoriafomina commented on Homework1/Sorting/Sorting/Program.cs
> +﻿using System;
Неиспользуемый _using_, уберите, пожалуйста.
Зато можно было бы написать `using Sorting;` и вместо `Sorting.ShellSort.Sort(intArray);` писать `ShellSort.Sort(intArray);`

2023-02-21 22:56 UTC, victoriafomina commented on Homework1/Sorting/Sorting/ShellSort.cs
> +﻿namespace Sorting;
Нужна пустая строка после namespace

2023-02-21 22:56 UTC, victoriafomina commented on Homework1/Sorting/Sorting/ShellSort.cs
> +	{
> К сожалению, только начиная с новых файлов будет нормальная табуляция ;(

Если утрировать, непоправленное замечание --> непройденный код ревью --> ваша фича не попала в релиз.

Я уверена, что вы справитесь применить `Shift + Tab` и заменить табы на пробелы :) Вероятно вашу проблему можно решить с помощью вашей IDE.

Добавила еще пару замечаний, про которые раньше не написала. Так что поправьте, пожалуйста, попытку снимать не буду

2023-02-21 22:56 UTC, victoriafomina commented on Homework1/Sorting/SortingTest/ShellSortTest.cs
> +        Assert.IsTrue(IsArraySorted(array));
Прошу прощения, _NUnit_ не пользовалась пару лет. В [документации пишут](https://github.com/nunit/nunit.analyzers/blob/master/documentation/NUnit2003.md), что сейчас лучше вместо _Assert.True_ использовать _Assert.That_

2023-02-21 22:56 UTC, victoriafomina commented on Homework1/Sorting/SortingTest/ShellSortTest.cs
> +            return false;
Можно еще лучше.
Судя по второй задаче вы уже научились использовать `Enumerable.SequenceEqual(..., ...)`. Давайте-ка сравним массивы через этот метод тогда

2023-02-22 17:56 UTC, victoriafomina requested changes

2023-02-22 17:56 UTC, victoriafomina commented on Homework1/Sorting/SortingTest/ShellSortTest.cs
> +    }
Мне все еще не нравится, что этот метод и сортирует один из массивов, и сравнивает их на равенство. Метод должен какую-то обособленную задачу выполнять. По названию вашего метода непонятно, что внутри еще и сортируется что-то.
Можно в принципе содержимое этого метода не выделять в отдельный метод

2023-02-22 17:56 UTC, victoriafomina commented on Homework1/Sorting/Sorting/ArrayUtils.cs
> +    public static class ArrayUtils
Класс нужно на 4 пробела влево сместить

2023-02-22 20:36 UTC, AlexPoziev commented on Homework1/Sorting/SortingTest/ShellSortTest.cs
> +    }
Проблему понял, метод изменял массив, который трогать был не должен, удалил вспомогательные методы для тестов, их можно было заменить двумя строками

2023-02-24 06:51 UTC, merged