BWT
AlexPoziev/SPBUHomeworkCSharp pull request #2
Opened 2023-02-19 07:14 UTC by AlexPoziev

2023-02-21 22:56 UTC, victoriafomina requested changes

2023-02-21 22:56 UTC, victoriafomina commented on Homework1/BWT/BWT/BWT/BWTUtils.cs
> +        public static bool IsSuffixMore(in string word, int firstSuffixIndex, int secondSuffixIndex)
Метод `IsSuffixMore` - это уже не сам API для того, чтобы пользоваться преобразованием Барроуза-Уилера, а детали его внутренней реализации.
Он должен быть приватным

2023-02-21 22:56 UTC, victoriafomina commented on Homework1/BWT/BWT/BWT/BWTUtils.cs
> +        public static void FillArrayBySequence(int[] array)
Этот метод не имеет никакого отношения к преобразованию Барроуза-Уилера. Стоит вынести его в отдельный класс, _ArrayUtils_, например

2023-02-22 00:40 UTC, AlexPoziev commented on Homework1/BWT/BWT/BWT/BWTUtils.cs
> +        public static bool IsSuffixMore(in string word, int firstSuffixIndex, int secondSuffixIndex)
Извините, на парах еще не совсем поясняли этот момент, как правильно "ругаться"? Так же как в C? Возвращать какую-то переменную и уже писать всякие гадости в Main? Или бросить exception ArgumentNullException с пояснением что и где пошло не так достаточно ?

2023-02-22 18:34 UTC, victoriafomina requested changes

2023-02-22 18:34 UTC, victoriafomina commented on Homework1/BWT/BWT/BWT/BWT.cs
> +        if (word == null)
Больше думайте про крайние случаи. _word_ вполне может быть пустой строкой. Это тоже ситуация, в которой стоит бросить исключения

2023-02-22 18:34 UTC, victoriafomina commented on Homework1/BWT/BWT/BWT/BWT.cs
> +    public static string InverseBWT(in string transformedString, int lastElementIndex)
Индекс может быть отрицательным (или больше возможного значения индекса), а строка пустой. В этих случаях тоже нужно поругаться

2023-02-22 18:34 UTC, victoriafomina commented on Homework1/BWT/BWT/BWT/BWTUtils.cs
> +    public static int DirectBWTSort(in string word, int[] array)
Опять же, строка может быть пустой, а массив некорректного размера или заполненным чем-то явно не тем. Надо проверять, что все в порядке

2023-02-22 18:34 UTC, victoriafomina commented on Homework1/BWT/BWT/BWT/BWTUtils.cs
> +    public static void InverseBWTSort(in string word, int[] ints)
Здесь то же самое. Проверьте, что переданные аргументы соответствуют вашим ожиданиям

2023-02-22 18:34 UTC, victoriafomina commented on Homework1/BWT/BWT/BWT/Program.cs
> +            var stringArray = parameters.Split();
А тут вы не проверяете, что _stringArray_ ожидаемого размера. И дальше как будто бы верите, что его длина не меньше 2.
В итоге если, например, ввести в качестве второй опции просто строку без пробелов, то на доступе к элементу массива можно свалиться c _IndexOutOfRangeException_

2023-02-22 18:34 UTC, victoriafomina commented on Homework1/BWT/BWT/BWT/BWTUtils.cs
> +        public static bool IsSuffixMore(in string word, int firstSuffixIndex, int secondSuffixIndex)
> Извините, на парах еще не совсем поясняли этот момент, как правильно "ругаться"? Так же как в C? Возвращать какую-то переменную и уже писать всякие гадости в Main? Или бросить exception ArgumentNullException с пояснением что и где пошло не так достаточно ?

Если в метод передается что-то некорректное, то да, обычно бросают исключение. И уже в месте вызова эти исключения [обрабатывают](https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/try-catch). Вы про это пока знать не обязаны, поэтому не требую от вас обрабатывать исключения.

То как вы после исправления "ругаетесь" на некорректные значения аргументов - вполне ок для первой домашки

2023-02-24 00:02 UTC, victoriafomina approved these changes

2023-02-24 06:50 UTC, merged